import {readFile, writeFile} from 'node:fs/promises';

const [launcher, bridge] = await Promise.all([
  readFile(new URL('../assets/claude-proxy', import.meta.url)),
  readFile(new URL('../assets/socks_http_bridge.py', import.meta.url)),
]);
const source = `// Generated by scripts/embed-assets.mjs. Do not edit.\n` +
  `export const launcherBase64 = ${JSON.stringify(launcher.toString('base64'))};\n` +
  `export const bridgeBase64 = ${JSON.stringify(bridge.toString('base64'))};\n`;
await writeFile(new URL('../src/embedded-assets.ts', import.meta.url), source);
